pipeline {
    agent any

    environment {
        DOCKER_HUB_CREDENTIALS = credentials('docker-hub-credentials')
    }

    stages {
        stage('Checkout') {
            steps {
                git 'https://github.com/BS-PMC-2024/BS-PMC-2024-Team20.git'
            }
        }
        stage('Build Docker Image') {
            steps {
                script {
                    docker.build("shimonbaruch/your-image-name", "src/connections/")
                }
            }
        }
        stage('Push to Docker Hub') {
            steps {
                script {
                    docker.withRegistry('', 'docker-hub-credentials') {
                        docker.image("shimonbaruch/your-image-name").push()
                    }
                }
            }
        }
    }
}
